# 自分で深層学習を実装してみる！！

# 3桁の２進数を、１０進数に変換するネット

In [4]:
import numpy as np
import matplotlib.pyplot as plt

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def identity_function(x):#恒等関数
    return x 

def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)#最大値で引くことで、オーバーフローを防ぐ
    sum_exp_a = np.sum(exp_a)
    y = exp_a /sum_exp_a
    return y


def change_one_hot(lst):
    # 最大値を取得
    max_value = np.max(lst)

    # 最大値だけ1、残りを0の配列に置き換える
    result = np.zeros(8)
    result[np.argmax(lst)] = 1

    return result

def sum_squared_error(y, t):#２乗和誤差
    return 0.5 * np.sum((y-t)**2)

def bibun_numerical_gradient(sum_squared_error, y, teach, w):#ここのｙは、順伝播した結果のことなので、入力値xの情報は入っている。
    h = 1e-4#0.0001
    loss = sum_squared_error(y, teach)

    return (sum_squared_error(w+h)-sum_squared_error(w-h))/(2*h)

def make_input():
    x0 = int(np.random.random()<0.5)
    x1 = int(np.random.random()<0.5)
    x2 = int(np.random.random()<0.5)
    teach = x2*4 + x1*2 + x0
    x  = np.array([x2,x1,x0])
    teach = np.array([[int(teach==0)],\
                      [int(teach==1)],\
                      [int(teach==2)],\
                      [int(teach==3)],\
                      [int(teach==4)],\
                      [int(teach==5)],\
                      [int(teach==6)],\
                      [int(teach==7)]])
    return x, teach



def init_network(): #3層のネットワークを定義
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5, 0.6, 0.7, 0.1, 0.2, 0.3], 
                              [0.2, 0.4, 0.6, 0.1, 0.3, 0.5, 0.6, 0.2], 
                              [0.3, 0.1, 0.2, 0.4, 0.2, 0.5, 0.1, 0.4], 
                              ]) #3つのニューロンから、8つのニューロンに出力する際の重み
    network['b1'] = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,]) #バイアスを8つのニューロンにたす


    network['W2'] = np.array([[0.1, 0.4, 0.5, 0.6, 0.7],
                              [0.2, 0.5, 0.5, 0.6, 0.7],
                              [0.3, 0.6, 0.5, 0.6, 0.7],
                              [0.2, 0.5, 0.5, 0.6, 0.7],
                              [0.3, 0.6, 0.5, 0.6, 0.7],
                              [0.2, 0.5, 0.5, 0.6, 0.7],
                              [0.3, 0.6, 0.5, 0.6, 0.7],
                              [0.2, 0.5, 0.5, 0.6, 0.7]]) #8つのニューロンから5つのニューロンに出力する際の重み
    
    network['b2'] = np.array([0.1, 0.2, 0.5, 0.3, 0.4])#5つのニューロンにたすバイアス
    network['W3'] = np.array([[0.1, 0.3, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
                              [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
                              [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
                              [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
                              [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7]]) #5つのニューロンから8つのニューロンに出力する際の重み
    network['b3'] = np.array([0.1, 0.2, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7]) #バイアスを8つのニューロンにたす

    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3'] #これらはinitに書くべきなきがする
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    print(a3)
    y = softmax (a3)

    return y


dw1 = []
dw2 = []
dw3 = []
# print(network['W1'])
x, teach = make_input()
network = init_network()
# x = np.array([1, 0, 0])
print(x)
y = forward(network, x)
error = sum_squared_error(y, teach) #かんすうをいれなきゃだめ

for i in range(10):
    x, teach = make_input()
    y = forward(network, x)

    for num in range(len(network['W1'])):#ノードの個数
        for i1 in range(len(network['W1'][1])):
            koubaiw1 = bibun_numerical_gradient(sum_squared_error, x, y, teach, network['W1'][num][i])#関数を引数に入れる場合は、関数名を引数に入れる。渡した材料で、関数の中で、入れた関数に引数を渡して使用する。

            dw11 = np.append(dw11, np.array[koubaiw1], axis(0))
        dw1 = np.append(dw11, np.array[koubaiw1], axis(0))

    for num in range(len(network['W2'])):
        for i2 in range(len(network['W2'][1])):
            koubaiw2 = bibun_numerical_gradient(error, network['W2'][num][i])

            dw21 = np.append(dw21, np.array[koubaiw1], axis(0))
        dw2 = np.append(dw21, np.array[koubaiw1], axis(0))

    for num in range(len(network['W3'])):
        for i3 in range(len(network['W3'][1])):
            koubaiw3 = bibun_numerical_gradient(error, network['W3'][num][i])

            dw31 = np.append(dw31, np.array[koubaiw3], axis(0))
        dw3 = np.append(dw31, np.array[koubaiw1], axis(0))

        # 微分して求めたそれぞれの傾きをもとに、重みを更新
    network['W1'] -= learning_rate * dW1
    network.W2 -= learning_rate * dW2
    network.W3 -= learning_rate * dW3
    dw1 = []
    dw2 = []
    dw3 = []


test_x, test_teach = make_input()
test = forward(network, test_x)



[1 0 1]
[0.96167371 2.00432145 2.11397162 3.52794324 3.05661937 3.52794324
 3.99926711 3.99926711]
[0.96801139 2.01876735 2.12613393 3.55226786 3.07688988 3.55226786
 4.02764584 4.02764584]
[0.01184425 0.03387233 0.0377115  0.15697697 0.09758474 0.15697697
 0.25251662 0.25251662]


TypeError: bibun_numerical_gradient() takes 2 positional arguments but 5 were given

In [9]:
import numpy as np

def change_one_hot(lst):
    # 最大値を取得
    max_value = np.max(lst)

    # 最大値だけ1、残りを0の配列に置き換える
    result = np.zeros(8)
    result[np.argmax(lst)] = 1

    return result


# ごっちゃになってしまったので、作り直し

In [3]:
import numpy as np
import matplotlib.pyplot as plt

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def identity_function(x):#恒等関数
    return x 

def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)#最大値で引くことで、オーバーフローを防ぐ
    sum_exp_a = np.sum(exp_a)
    y = exp_a /sum_exp_a
    return y


def change_one_hot(lst):
    # 最大値を取得
    max_value = np.max(lst)

    # 最大値だけ1、残りを0の配列に置き換える
    result = np.zeros(8)
    result[np.argmax(lst)] = 1

    return result

def sum_squared_error(y, t):#２乗和誤差
    return 0.5 * np.sum((y-t)**2)


def make_input():
    x0 = int(np.random.random()<0.5)
    x1 = int(np.random.random()<0.5)
    x2 = int(np.random.random()<0.5)
    teach = x2*4 + x1*2 + x0
    x  = np.array([x2,x1,x0])
    teach = np.array([[int(teach==0)],\
                      [int(teach==1)],\
                      [int(teach==2)],\
                      [int(teach==3)],\
                      [int(teach==4)],\
                      [int(teach==5)],\
                      [int(teach==6)],\
                      [int(teach==7)]])
    return x, teach



def init_network(): #3層のネットワークを定義
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5, 0.6, 0.7, 0.1, 0.2, 0.3], 
                              [0.2, 0.4, 0.6, 0.1, 0.3, 0.5, 0.6, 0.2], 
                              [0.3, 0.1, 0.2, 0.4, 0.2, 0.5, 0.1, 0.4], 
                              ]) #3つのニューロンから、8つのニューロンに出力する際の重み
    network['b1'] = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,]) #バイアスを8つのニューロンにたす


    network['W2'] = np.array([[0.1, 0.4, 0.5, 0.6, 0.7],
                              [0.2, 0.5, 0.5, 0.6, 0.7],
                              [0.3, 0.6, 0.5, 0.6, 0.7],
                              [0.2, 0.5, 0.5, 0.6, 0.7],
                              [0.3, 0.6, 0.5, 0.6, 0.7],
                              [0.2, 0.5, 0.5, 0.6, 0.7],
                              [0.3, 0.6, 0.5, 0.6, 0.7],
                              [0.2, 0.5, 0.5, 0.6, 0.7]]) #8つのニューロンから5つのニューロンに出力する際の重み
    
    network['b2'] = np.array([0.1, 0.2, 0.5, 0.3, 0.4])#5つのニューロンにたすバイアス
    network['W3'] = np.array([[0.1, 0.3, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
                              [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
                              [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
                              [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
                              [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7]]) #5つのニューロンから8つのニューロンに出力する際の重み
    network['b3'] = np.array([0.1, 0.2, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7]) #バイアスを8つのニューロンにたす

    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3'] #これらはinitに書くべきなきがする
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    print(a3)
    y = softmax (a3)

    return y

def bibun_numerical_gradient(sum_squared_error ,ywh1, ywh2):#ここのｙは、順伝播した結果のことなので、入力値xの情報は入っている。
    h = 1e-4#0.0001

    return (sum_squared_error(ywh1)-sum_squared_error(ywh2))/(2*h)




dw1 = []
dw2 = []
dw3 = []
# print(network['W1'])
x, teach = make_input()
network = init_network()
# x = np.array([1, 0, 0])
print(x)
y = forward(network, x)
error = sum_squared_error(y, teach) #かんすうをいれなきゃだめ

for i in range(10):
    x, teach = make_input()
    y1 = forward(network, x)
    y2 = forward(network, x)

    for num in range(len(network['W1'])):#ノードの個数
        for i1 in range(len(network['W1'][1])):
            koubaiw1 = bibun_numerical_gradient(sum_squared_error, , network['W1'][num][i])#関数を引数に入れる場合は、関数名を引数に入れる。渡した材料で、関数の中で、入れた関数に引数を渡して使用する。

            dw11 = np.append(dw11, np.array[koubaiw1], axis(0))
        dw1 = np.append(dw11, np.array[koubaiw1], axis(0))

    for num in range(len(network['W2'])):
        for i2 in range(len(network['W2'][1])):
            koubaiw2 = bibun_numerical_gradient(error, network['W2'][num][i])

            dw21 = np.append(dw21, np.array[koubaiw1], axis(0))
        dw2 = np.append(dw21, np.array[koubaiw1], axis(0))

    for num in range(len(network['W3'])):
        for i3 in range(len(network['W3'][1])):
            koubaiw3 = bibun_numerical_gradient(error, network['W3'][num][i])

            dw31 = np.append(dw31, np.array[koubaiw3], axis(0))
        dw3 = np.append(dw31, np.array[koubaiw1], axis(0))

        # 微分して求めたそれぞれの傾きをもとに、重みを更新
    network['W1'] -= learning_rate * dW1
    network.W2 -= learning_rate * dW2
    network.W3 -= learning_rate * dW3
    dw1 = []
    dw2 = []
    dw3 = []


test_x, test_teach = make_input()
test = forward(network, test_x)



SyntaxError: invalid syntax (1216691841.py, line 118)

In [5]:
import numpy as np
import pprint
def set_network(w1,b1,w2,b2,w3,b3):
    network = [w1,b1,w2,b2,w3,b3]
    return network




w1 = np.array([[0.1, 0.3, 0.5, 0.6, 0.7, 0.1, 0.2, 0.3], 
                              [0.2, 0.4, 0.6, 0.1, 0.3, 0.5, 0.6, 0.2], 
                              [0.3, 0.1, 0.2, 0.4, 0.2, 0.5, 0.1, 0.4], 
                              ]) #3つのニューロンから、8つのニューロンに出力する際の重み
b1 = np.array([[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,]]) #バイアスを8つのニューロンにたす


w2 = np.array([[0.1, 0.4, 0.5, 0.6, 0.7],
                              [0.2, 0.5, 0.5, 0.6, 0.7],
                              [0.3, 0.6, 0.5, 0.6, 0.7],
                              [0.2, 0.5, 0.5, 0.6, 0.7],
                              [0.3, 0.6, 0.5, 0.6, 0.7],
                              [0.2, 0.5, 0.5, 0.6, 0.7],
                              [0.3, 0.6, 0.5, 0.6, 0.7],
                              [0.2, 0.5, 0.5, 0.6, 0.7]]) #8つのニューロンから5つのニューロンに出力する際の重み
    
b2 = np.array([[0.1, 0.2, 0.5, 0.3, 0.4]])#5つのニューロンにたすバイアス
w3 = np.array([[0.1, 0.3, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
                    [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
                    [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
                    [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
                    [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7]]) #5つのニューロンから8つのニューロンに出力する際の重み
b3 = np.array([[0.1, 0.2, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7]]) #バイアスを8つのニューロンにたす

network = set_network(w1,b1,w2,b2,w3,b3)
pprint.pprint(network)
print("-------------------------------------------")
network[1][0][0] += 0.001
pprint.pprint(network)
print(len(network))

network1_zeros = [np.zeros_like(w1), np.zeros_like(b1), np.zeros_like(w2), np.zeros_like(b2), np.zeros_like(w3), np.zeros_like(b3)]

print(network1_zeros)



[array([[0.1, 0.3, 0.5, 0.6, 0.7, 0.1, 0.2, 0.3],
       [0.2, 0.4, 0.6, 0.1, 0.3, 0.5, 0.6, 0.2],
       [0.3, 0.1, 0.2, 0.4, 0.2, 0.5, 0.1, 0.4]]),
 array([[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]]),
 array([[0.1, 0.4, 0.5, 0.6, 0.7],
       [0.2, 0.5, 0.5, 0.6, 0.7],
       [0.3, 0.6, 0.5, 0.6, 0.7],
       [0.2, 0.5, 0.5, 0.6, 0.7],
       [0.3, 0.6, 0.5, 0.6, 0.7],
       [0.2, 0.5, 0.5, 0.6, 0.7],
       [0.3, 0.6, 0.5, 0.6, 0.7],
       [0.2, 0.5, 0.5, 0.6, 0.7]]),
 array([[0.1, 0.2, 0.5, 0.3, 0.4]]),
 array([[0.1, 0.3, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
       [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
       [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
       [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7],
       [0.2, 0.4, 0.3, 0.6, 0.5, 0.6, 0.7, 0.7]]),
 array([[0.1, 0.2, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7]])]
-------------------------------------------
[array([[0.1, 0.3, 0.5, 0.6, 0.7, 0.1, 0.2, 0.3],
       [0.2, 0.4, 0.6, 0.1, 0.3, 0.5, 0.6, 0.2],
       [0.3, 0.1, 0.2, 0.4, 0.2, 0.5, 0.1, 

In [8]:
import numpy as np
import pprint


#ニューラルネットワークを作る関数
def set_network(w1,b1,w2,b2,w3,b3):
    network = [w1,b1,w2,b2,w3,b3] #list
    return network

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0, x)

def identity_function(x):#恒等関数
    return x 

def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)#最大値で引くことで、オーバーフローを防ぐ
    sum_exp_a = np.sum(exp_a)
    y = exp_a /sum_exp_a
    return y



def forward(network, in_x):
    W1, W2, W3 = network[0], network[2], network[4] #　　　名前か番号か迷う
    b1, b2, b3 = network[1], network[3], network[5]

    a1 = np.dot(in_x, W1) + b1
    z1 = relu(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = relu(a2)
    a3 = np.dot(z2, W3) + b3
    # print(a3)
    y = softmax (a3)

    return y #xを入力したnetworkで順伝播して得られた出力結果






def sum_squared_error(y, t):#２乗和誤差
    return 0.5 * np.sum((y-t)**2)

def bibun_numerical_gradient(out_y1, out_y2):
    return (out_y1 - out_y2)/(2*h)




def make_input():
    x0 = int(np.random.random()<0.5)
    x1 = int(np.random.random()<0.5)
    x2 = int(np.random.random()<0.5)
    teach = x2*4 + x1*2 + x0
    x  = np.array([x2,x1,x0])
    teach = np.array([[int(teach==0)],\
                      [int(teach==1)],\
                      [int(teach==2)],\
                      [int(teach==3)],\
                      [int(teach==4)],\
                      [int(teach==5)],\
                      [int(teach==6)],\
                      [int(teach==7)]])
    return x, teach




#初期の重みとバイアスを記入
w1 = np.array([[0.1, 0.3, 0.5, 0.6, 0.7, 0.1, 0.2, 0.3], 
               [0.2, 0.4, 0.6, 0.1, 0.3, 0.5, 0.6, 0.2], 
               [0.3, 0.1, 0.2, 0.4, 0.2, 0.5, 0.1, 0.4]]) #3つのニューロンから、8つのニューロンに出力する際の重み
w1 = np.random.random([3,8])*0.01

b1 = np.array([[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,]]) #バイアスを8つのニューロンにたす
b1 = np.random.random([1,8])*0.01

w2 = np.array([[0.1, 0.4, 0.5, 0.6, 0.7],
               [0.2, 0.5, 0.1, 0.8, 0.1],
               [0.3, 0.6, 0.2, 0.5, 0.2],
               [0.2, 0.5, 0.4, 0.2, 0.3],
               [0.3, 0.6, 0.7, 0.3, 0.2],
               [0.2, 0.5, 0.3, 0.2, 0.5],
               [0.3, 0.6, 0.1, 0.1, 0.1],
               [0.2, 0.5, 0.1, 0.1, 0.2]]) #8つのニューロンから5つのニューロンに出力する際の重み
w2 = np.random.random([8,5])*0.01

b2 = np.array([[0.1, 0.2, 0.2, 0.4, 0.4]])#5つのニューロンにたすバイアス
b2 = np.random.random([1,5])*0.01

w3 = np.array([[0.1, 0.3, 0.3, 0.3, 0.2, 0.1, 0.5, 0.1],
               [0.2, 0.2, 0.1, 0.2, 0.1, 0.4, 0.2, 0.4],
               [0.6, 0.6, 0.5, 0.5, 0.5, 0.5, 0.3, 0.7],
               [0.3, 0.4, 0.3, 0.4, 0.7, 0.3, 0.4, 0.7],
               [0.1, 0.1, 0.7, 0.1, 0.3, 0.2, 0.1, 0.2]]) #5つのニューロンから8つのニューロンに出力する際の重み
w3 = np.random.random([5,8])*0.01

b3 = np.array([[0.3, 0.2, 0.2, 0.3, 0.7, 0.2, 0.1, 0.3]]) #バイアスを8つのニューロンにたす
b3 = np.random.random([1,8])*0.01

#微小量hを定義
h = 1e-4#0.0001
#学習率を定義
learning_rate = 0.1
#学習回数を定義
learn = 12000


Network = set_network(w1,b1,w2,b2,w3,b3)#初期ネットワーク作成
in_x, teach = make_input()#入力データと教師信号作成
out = forward(Network, in_x)#順伝播
error = sum_squared_error(out,teach) #出力と教師を比較して誤差を計算
# koubai_list = [[[[0] * len()] * len(Network[])] * 1] * len(Network) # koubai_list = np.zeros_like(Network)#koubai_list = [[[]]] #np.zerosのほうがよさそうなので変えた

koubai_list = [np.zeros_like(w1), np.zeros_like(b1), np.zeros_like(w2), np.zeros_like(b2), np.zeros_like(w3), np.zeros_like(b3)]
koubai_list = np.array(koubai_list)
print("firstnetwork")
pprint.pprint(Network)

#繰り返し処理
for i in range(learn):
    in_x, teach = make_input()#入力データと教師信号作成
    
    for param in range(len(Network)): #パラメータの種類数だけ繰り返す　本来はlen(Network)的な感じになる　やり方わからなかった
        for gyou in range(len(Network[param])): #w1的な感じつまり行数サイズ取得 network0番目の、行数を取得？
            for retsu in range(len(Network[param][gyou])): #列数サイズ取得

                # Network1 = Network #コピーを作る
                Network1 = Network.copy()
                # print(Network1[param][gyou][retsu])
                Network1[param][gyou][retsu] += h #あるひとつのパラメータだけちょっと増やしたNetworkを作る ここはこうか？→（リストw1の一つの要素だけに+hしてから、set_networkで作る？そんなきがする）
                # pprint.pprint(Network1)
                out_y1 = forward(Network1,in_x)#そのNetworkで順伝播して出力を得る
                loss1 = sum_squared_error(out_y1,teach) #出力と教師データを比較し、誤差を計算する

                # Network2 = Network #コピーを作る
                Network2 = Network.copy()
                Network2[param][gyou][retsu] -= h #あるひとつのパラメータだけちょっと減らしたNetworkを作る
                out_y2 = forward(Network2,in_x)#そのNetworkで順伝播して出力を得る
                loss2 = sum_squared_error(out_y2,teach) #出力と教師データを比較し、誤差を計算する

                koubai = bibun_numerical_gradient(loss1,loss2) #２つの誤差から、勾配を求める（損失関数の微分値が求まる）
                # print("----------------------------------")
                # pprint.pprint(koubai_list)
                # print(loss1)
                # print(loss2)

                # koubai_list = Network #コピーを作る
                # koubai_list - Network #引くことで、要素全部０の同じ形のリストを作成する！

                koubai_list[param][gyou][retsu] = koubai #勾配情報をリストに保存する　これを繰り返すと、各パラメータの勾配のリストが完成する


    # Network -= koubai_list * learning_rate #パラメータを更新
    for param in range(len(Network)):
        Network[param] -= koubai_list[param] * learning_rate

    # print("success")

A = forward(Network,in_x)
print("------endnetwork-------")
pprint.pprint(Network)
print(teach)
print(in_x)
print(A)






    # あるひとつのパラメータだけちょっと増やしたNetworkを作って、順伝播する
    # あるひとつのパラメータだけちょっと減らしたNetworkを作って、順伝播する
    # その二つの値を教師データと比較し、誤差を計算する
    # それらの変化量から、ある一つのパラメータの勾配を求める。そしてリストにまとめる

    # これらをすべてのパラメータで一つ一つやって(for文)、勾配のリストを完成させる

    # 勾配のリストに学習率をかけた者を、今のパラメータから引いて更新する

    # 更新後のパラメータで新たなNetworkを作成する



C:\Users\atusi\AppData\Local\Temp\ipykernel_3756\1733197875.py:122: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  koubai_list = np.array(koubai_list)


firstnetwork
[array([[0.00799036, 0.00453921, 0.00341678, 0.00170127, 0.00254634,
        0.00141982, 0.00261657, 0.00163408],
       [0.00902119, 0.00509929, 0.00418483, 0.00739426, 0.00543911,
        0.00272091, 0.00017467, 0.00507561],
       [0.00313419, 0.00914139, 0.00197424, 0.00920458, 0.00547446,
        0.00295546, 0.00647579, 0.00522669]]),
 array([[0.00410862, 0.0003382 , 0.0097739 , 0.00648914, 0.00903936,
        0.00320203, 0.00980392, 0.00065487]]),
 array([[4.65839381e-04, 1.93139377e-04, 5.56520349e-03, 1.74615945e-03,
        5.46230497e-04],
       [4.71529994e-03, 7.63595279e-03, 5.55569652e-03, 8.73855038e-03,
        7.32493512e-04],
       [4.61891059e-03, 7.48964230e-03, 4.88878401e-03, 7.04188084e-03,
        5.62478730e-03],
       [9.43795665e-05, 8.83435165e-03, 5.85794614e-03, 4.20888990e-03,
        9.51594935e-04],
       [4.56095483e-03, 8.92083527e-03, 1.39158652e-03, 5.94305025e-03,
        1.38068864e-03],
       [1.01490946e-03, 6.57150378e-03, 9.2

In [4]:
import numpy as np
import pprint


#ニューラルネットワークを作る関数
def set_network(w1,b1,w2,b2,w3,b3):
    network = [w1,b1,w2,b2,w3,b3] #list
    return network






w1 = np.array([[0.1, 0.3, 0.5, 0.6, 0.7, 0.1, 0.2, 0.3], 
               [0.2, 0.4, 0.6, 0.1, 0.3, 0.5, 0.6, 0.2], 
               [0.3, 0.1, 0.2, 0.4, 0.2, 0.5, 0.1, 0.4]]) #3つのニューロンから、8つのニューロンに出力する際の重み
b1 = np.array([[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,]]) #バイアスを8つのニューロンにたす
w2 = np.array([[0.1, 0.4, 0.5, 0.6, 0.7],
               [0.2, 0.5, 0.1, 0.8, 0.1],
               [0.3, 0.6, 0.2, 0.5, 0.2],
               [0.2, 0.5, 0.4, 0.2, 0.3],
               [0.3, 0.6, 0.7, 0.3, 0.2],
               [0.2, 0.5, 0.3, 0.2, 0.5],
               [0.3, 0.6, 0.1, 0.1, 0.1],
               [0.2, 0.5, 0.1, 0.1, 0.2]]) #8つのニューロンから5つのニューロンに出力する際の重み
b2 = np.array([[0.1, 0.2, 0.2, 0.4, 0.4]])#5つのニューロンにたすバイアス
w3 = np.array([[0.1, 0.3, 0.3, 0.3, 0.2, 0.1, 0.5, 0.1],
               [0.2, 0.2, 0.1, 0.2, 0.1, 0.4, 0.2, 0.4],
               [0.6, 0.6, 0.5, 0.5, 0.5, 0.5, 0.3, 0.7],
               [0.3, 0.4, 0.3, 0.4, 0.7, 0.3, 0.4, 0.7],
               [0.1, 0.1, 0.7, 0.1, 0.3, 0.2, 0.1, 0.2]]) #5つのニューロンから8つのニューロンに出力する際の重み
b3 = np.array([[0.3, 0.2, 0.2, 0.3, 0.7, 0.2, 0.1, 0.3]]) #バイアスを8つのニューロンにたす


Network = set_network(w1,b1,w2,b2,w3,b3)#初期ネットワーク作成

pprint.pprint(Network)

















w1 = np.random.random([3,8])
b1 = np.random.random([1,8])
w2 = np.random.random([8,5])
b2 = np.random.random([1,5])
w3 = np.random.random([5,8])
b3 = np.random.random([1,8])

Network = set_network(w1,b1,w2,b2,w3,b3)#初期ネットワーク作成

print("--------------------------------------------------")
pprint.pprint(Network)

[array([[0.1, 0.3, 0.5, 0.6, 0.7, 0.1, 0.2, 0.3],
       [0.2, 0.4, 0.6, 0.1, 0.3, 0.5, 0.6, 0.2],
       [0.3, 0.1, 0.2, 0.4, 0.2, 0.5, 0.1, 0.4]]),
 array([[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]]),
 array([[0.1, 0.4, 0.5, 0.6, 0.7],
       [0.2, 0.5, 0.1, 0.8, 0.1],
       [0.3, 0.6, 0.2, 0.5, 0.2],
       [0.2, 0.5, 0.4, 0.2, 0.3],
       [0.3, 0.6, 0.7, 0.3, 0.2],
       [0.2, 0.5, 0.3, 0.2, 0.5],
       [0.3, 0.6, 0.1, 0.1, 0.1],
       [0.2, 0.5, 0.1, 0.1, 0.2]]),
 array([[0.1, 0.2, 0.2, 0.4, 0.4]]),
 array([[0.1, 0.3, 0.3, 0.3, 0.2, 0.1, 0.5, 0.1],
       [0.2, 0.2, 0.1, 0.2, 0.1, 0.4, 0.2, 0.4],
       [0.6, 0.6, 0.5, 0.5, 0.5, 0.5, 0.3, 0.7],
       [0.3, 0.4, 0.3, 0.4, 0.7, 0.3, 0.4, 0.7],
       [0.1, 0.1, 0.7, 0.1, 0.3, 0.2, 0.1, 0.2]]),
 array([[0.3, 0.2, 0.2, 0.3, 0.7, 0.2, 0.1, 0.3]])]
--------------------------------------------------
[array([[0.9533489 , 0.7196298 , 0.46464161, 0.15467105, 0.08737698,
        0.83780278, 0.73027956, 0.29535714],
       [0.62997441, 0